### ISSUE TITLE
If the first argument is a function definition.

### ISSUE THREAD

**Issue by unc0** [kkirby/gorillascript#2]
```
set-timeout #
  console.log 'test'
  , 500_ms
```

It won't compile.

```
set-timeout (#
  console.log 'test'
), 500_ms
```

It won't compile.

Here is my proposal:

```
set-timeout #{
  console.log 'test'
}, 500_ms
```

**Comment by kkirby** [comment]
There is actually a syntax that does work:

```
setTimeout(
    #
        doSomething()
    1000
)
```

If you provide the parenthesis, GorillaScript will treat each new line as an argument without the use of commas.
