### ISSUE TITLE
Doesn't build with recent nodejs versions

### ISSUE THREAD

**Issue by vendethiel** [kkirby/gorillascript#6]
Hi, it seems like this doesn't build anymore on more recent nodejs versions.

The easy-to-fix errors are:
- Change `tmp-dir`/`tmpDir` to `tmpdir`.
- Change `vm.Script.foo` to `vm.foo`
- `Map`/`WeakMap` need to be instantiated with `new`, not just called.

These are easy enough to fix, but there's an extra failure in the promises-aplus compliance tests that I don't know how to fix.

**Comment by kkirby** [comment]
Yeah, it looks like grunt-gorilla needs to be forked and updated to use this code. As of right now, it's using the older gorillascript to compile. If I have time and energy I'll look into update grunt-gorilla.

Out of curiosity, what are you using gorillascript for? I've mostly migrated away from it in favor of TypeScript.

**Comment by vendethiel** [comment]
> Out of curiosity, what are you using gorillascript for? I've mostly migrated away from it in favor of TypeScript.

Eh, I'm not really using it, I've just [found it interesting for a long time](https://github.com/kkirby/gorillascript/commit/c372a4bed9b1055ad45b86e750b30df3f39e93e9#commitcomment-18976644). The only thing it really lacks is static typechecking, and I've considered more than once trying to output TypeScript code instead of simple JS to get compile-time typechecking along with the nice syntax GS has.

**Comment by kkirby** [comment]
That was way more work than I had anticipated. The recursive dependency of gorillascript is weird. Anyway, this is fixed.
